### ISSUE TITLE
C# client 1.7.0 failing to install via nuget

### ISSUE THREAD

**Issue by rajivkukreja** [rosette-api/csharp#76]
Greetings -

Quick note to let you know that the nuget installation of the rosette API client fails with an error messaging saying:

`Failed to add reference to 'System.IO'. Please make sure it is in the Global Assembly Cache`.

I don't believe there is a `System.IO.dll` assembly in the .NET Framework that one can even add as a reference. It certainly is not found anywhere in the GAC. There is a `System.IO` namespace but I think it is in the `System.dll` assembly.

This is in a C# project targeting the `.NET Framework 4.6.1`.

Thanks

**Comment by cp2boston** [comment]
In looking at this, it appears that `rosette-api` requires `Newtonsoft`.  Other than that, I tried creating both a WPF app and Console App, 4.6.1, and had no problem installing rosette-api.  What kind of project do you have?

**Comment by rajivkukreja** [comment]
I have a regular Class Library project (using the Visual Studio 2015.. which shouldn't matter) and it does already reference Newtonsoft v10.0.3.

**Comment by cp2boston** [comment]
The nuspec file is constructed poorly and includes frameworkAssemblies that shouldn't be there.  I'll need to issue a new release, probably tomorrow if not by the end of today.  Sorry about that!

**Comment by cp2boston** [comment]
Please try rosette-api 1.7.2 from Nuget and let me know.  Thanks!

**Comment by rajivkukreja** [comment]
That worked. Thank you!

**Comment by cp2boston** [comment]
Nice!  Thanks for letting us know!
