### ISSUE TITLE
C# Rosette Client binds to a specific version of System.Net.Http?

### ISSUE THREAD

**Issue by rajivkukreja** [rosette-api/csharp#77]
I am in a Class Library project (targeting the `.NET Framework 4.6.1`) and already referencing `System.Net.Http 4.3.2` (a nuget package).

But the Rosette C# Client is throwing this exception:
`System.IO.FileLoadException: Could not load file or assembly 'System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`

**Comment by cp2boston** [comment]
I apologize for taking so long to answer this.  Are you still having this issue?  I tried creating a class library targeting 4.6.1 and did not have any trouble referencing and building with the binding.

**Comment by rajivkukreja** [comment]
No worries. I'm not sure - basically not using this client library ... pretty easy to go direct against the REST API... so thats what we are doing.
