### ISSUE TITLE
Entity with trailing dot "."?

### ISSUE THREAD

**Issue by PeterRakke** [rosette-api/csharp#84]
Hi Rosette,

I'm testing your API from .Net and I'm wondering if this result as expected/correct:
- It is a Dutch sentence so language is set to Dutch
- Input text is: "Michelle is getrouwd met Peter."

Rosette returns two entities, the second being "Peter." I didn't expect the trailing "." dot.

Is this expected behavior?

Kind regards,

Peter Rakké

**Comment by cp2boston** [comment]
Hi Peter, Interesting question.  I'll need to run it through our entity folks and get back to you.

**Comment by cp2boston** [comment]
Update: The team has determined that you found a bug in the underlying entity extraction logic and has logged a story to investigate.  So, it is not expected behavior, but is independent of the C# binding itself.  We can keep this issue open and I'll notify you when a resolution has been made.

**Comment by PeterRakke** [comment]
Thanks for the update 😊

Kind regards,

Peter Rakké

Van: Christopher Park <notifications@github.com>
Verzonden: maandag 19 maart 2018 14:56
Aan: rosette-api/csharp <csharp@noreply.github.com>
CC: PeterRakke <peterrakke@outlook.com>; Author <author@noreply.github.com>
Onderwerp: Re: [rosette-api/csharp] Entity with trailing dot "."? (#84)


Update: The team has determined that you found a bug in the underlying entity extraction logic and has logged a story to investigate. So, it is not expected behavior, but is independent of the C# binding itself. We can keep this issue open and I'll notify you when a resolution has been made.

**Comment by guruxu** [comment]
TEJ-1348

**Comment by seth-mg** [comment]
Closing stale issue.
